# Generated by Django 6.0.5 on 2026-05-07 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('published_date', models.DateField()),
                ('distribution_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('authors', models.ManyToManyField(to='expense_tracker.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expense_tracker.category')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expense_tracker.publisher')),
            ],
        ),
    ]
